import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateOpportunity,deadlineState,detectSensitiveText,validateProfile} from '../lib/engine.mjs';
import {opportunities,demoProfile} from '../data/opportunities.mjs';
import {prepareDraft,assembleDraft,exportBrief} from '../lib/drafts.mjs';
const now=new Date('2026-10-07T12:00:00Z'),glc=opportunities[0];
test('graduate core fit remains provisional until leadership and availability are supplied',()=>{const f=evaluateOpportunity(glc,demoProfile,now);assert.equal(f.status,'Likely fit');assert.equal(f.reviewNeeded,true);assert.equal(f.checks.find(x=>x.label==='Leadership example').status,'unknown');});
test('exact birthday is needed when birth-year bounds cross the age limit',()=>{const f=evaluateOpportunity(glc,{...demoProfile,birthYear:2005},now);assert.equal(f.checks[0].status,'unknown');});
test('age clearly below the range is ineligible',()=>{const f=evaluateOpportunity(glc,{...demoProfile,birthYear:2008},now);assert.equal(f.status,'Not eligible');assert.equal(f.canDraft,false);});
test('date-only deadline does not invent an organizer timezone on closing day',()=>{assert.equal(deadlineState({date:'2026-10-07',precision:'date'},now).kind,'verify');});
test('precise timestamp closes at the actual boundary',()=>{assert.equal(deadlineState({date:'2026-10-07',precision:'instant',instant:'2026-10-07T11:59:00Z'},now).kind,'closed');});
test('invalid deadline is explicit unknown',()=>{assert.equal(deadlineState({date:'invalid'},now).kind,'unknown');});
test('old evidence needs rechecking even if the deadline is open',()=>{const f=evaluateOpportunity({...glc,checkedAt:'2026-09-01'},demoProfile,now);assert.equal(f.status,'Recheck source');assert.equal(f.stale,true);});
test('reimbursement creates a blocker when travel cannot be fronted',()=>{const f=evaluateOpportunity(opportunities[2],demoProfile,now);assert.equal(f.status,'Upfront costs');assert.equal(f.checks[0].status,'funding');});
test('a self-reported funding plan clears only the cashflow blocker',()=>{const f=evaluateOpportunity(opportunities[2],{...demoProfile,canFrontTravel:true},now);assert.equal(f.status,'Likely fit');assert.equal(f.checks[0].status,'reported');});
test('training is a prerequisite, not an awarded fellowship',()=>{assert.equal(evaluateOpportunity(opportunities[1],demoProfile,now).status,'Training first');});
test('no current enrollment means a student-only program is excluded',()=>{const f=evaluateOpportunity({...glc,rules:{student:true}},demoProfile,now);assert.equal(f.status,'Not eligible');});
test('invalid profile numbers and booleans are rejected',()=>{assert.throws(()=>validateProfile({...demoProfile,weeklyHours:999}),/Weekly/);assert.throws(()=>validateProfile({...demoProfile,degreeCompleted:'yes'}),/Invalid/);});
test('credential and email detection returns categories only',()=>{const token='gh'+'p_'+'z'.repeat(36);assert.deepEqual(detectSensitiveText(token),['GitHub credential']);assert.deepEqual(detectSensitiveText('person'+'@'+'example.com'),['Email address']);});
test('sensitive profile content is stopped before local or gateway inference',()=>{assert.throws(()=>prepareDraft(glc,{...demoProfile,leadershipAction:'Contact me at '+'person'+'@'+'example.com'},now),/sensitive/);});
test('model may not invent fact identifiers',()=>{const {catalog}=prepareDraft(glc,demoProfile,now);assert.throws(()=>assembleDraft({openingId:'career',factIds:['profile.award'],closingId:'learning'},catalog),/unknown fact/);});
test('model prose cannot override fixed grounded statements',()=>{const {catalog,plan}=prepareDraft(glc,demoProfile,now);const d=assembleDraft({...plan,prose:'I won every award and travel is guaranteed.'},catalog);assert.ok(!d.text.includes('won'));assert.ok(!d.text.includes('guaranteed'));});
test('template retains self-report provenance and omits absent achievements',()=>{const {catalog,plan}=prepareDraft(glc,demoProfile,now);const d=assembleDraft(plan,catalog);assert.ok(d.facts.every(x=>x.kind==='self-reported'));assert.ok(!d.facts.some(x=>x.id==='profile.action'));assert.ok(d.text.includes('12 months'));});
test('export keeps conditional funding and source timestamp visible',()=>{const {catalog,plan,fit}=prepareDraft(glc,demoProfile,now);const b=exportBrief(glc,demoProfile,assembleDraft(plan,catalog),fit,now);assert.ok(b.includes('top three teams'));assert.ok(b.includes(glc.source));assert.ok(b.includes('not a submitted application'));assert.ok(b.includes('timezone has not been verified'));});
test('closed or ineligible opportunities cannot get an application draft',()=>{assert.throws(()=>prepareDraft(glc,{...demoProfile,degreeCompleted:false},now),/does not meet/);});
