import {formatDate} from '../../lib/engine.mjs';
function EvidenceCheck({check}) {
  const ok=['pass','reported'].includes(check.status);
  return <div className="evidence-row"><span className={'check-symbol '+(ok?'teal':'amber')} aria-hidden="true">{ok?<svg viewBox="0 0 24 24"><path d="m5 12 4 4 10-10"/></svg>:<svg viewBox="0 0 24 24"><path d="M12 5v8"/><circle cx="12" cy="18" r=".8"/></svg>}</span><div><strong>{check.label}</strong><p>{check.detail}</p></div></div>;
}
export default function OpportunityDetail({op,fit,tab,onTab,draft,onDraft,busy,error,provider,model,onModel,useAI,onAI}) {
  return <section className="detail-pane" aria-label="Selected opportunity">
    <p className="organizer">{op.organizer}</p><h2>{op.name}</h2><p className="tagline">{op.tagline}</p>
    <dl className="program-facts"><div><dt>{op.deadline.label||'Deadline'}</dt><dd>{formatDate(op.deadline.date)}</dd></div><div><dt>Format</dt><dd>{op.format}</dd></div><div><dt>Travel</dt><dd>{op.funding.travel}</dd></div></dl>
    <div className="detail-tabs" role="tablist" aria-label="Opportunity details">{['Eligibility & funding','Application draft'].map(x=><button key={x} role="tab" aria-selected={tab===x} className={tab===x?'active':''} onClick={()=>onTab(x)}>{x}</button>)}</div>
    {tab==='Eligibility & funding'?<div className="tab-content"><h3>Your fit, explained</h3><div className="evidence-checks">{fit.checks.map(x=><EvidenceCheck key={x.label} check={x}/>)}</div><div className={'funding-band '+(op.funding.type==='reimbursement'?'warning':'')}><strong>{op.funding.headline}</strong><p>{op.funding.detail}</p></div>{fit.stale&&<p className="inline-warning">This evidence is over 14 days old. Recheck the official source.</p>}{fit.deadline.kind==='verify'&&<p className="inline-warning">The organizer's closing timezone is unverified. Check the exact time before applying.</p>}</div>:<div className="tab-content draft-content"><h3>Write from evidence</h3><p className="muted">Drafts use your reported facts and cited organizer information. Review every statement before submitting.</p>
      <div className="model-options"><label><input type="checkbox" checked={useAI} disabled={!provider.available} onChange={e=>onAI(e.target.checked)}/> Use local AI to choose the writing plan</label>{useAI&&<select aria-label="Local AI model" value={model} onChange={e=>onModel(e.target.value)}>{provider.models.map(m=><option key={m}>{m}</option>)}</select>}<p>{provider.available?'Only fact identifiers are sent to your local provider. Profile text stays in the app.':'Local AI is offline. Template drafting is available and clearly labeled.'}</p></div>
      {draft?<><div className="draft-label"><span className="status blue">{draft.provider==='local-ai'?'Local AI plan':'Template draft'}</span><span>{draft.wordCount} words</span></div><div className="draft-text">{draft.text}</div><h4>Statements used</h4><ul className="fact-references">{draft.facts.map(f=><li key={f.id}><code>{f.id}</code><span>{f.kind==='organizer'?<a href={f.source} target="_blank" rel="noreferrer">Organizer source</a>:'Your reported fact'}</span></li>)}</ul></>:<div className="draft-empty"><strong>Your first draft starts with real facts.</strong><p>Prepare a brief, then edit it in your own voice. Missing achievements are never filled in for you.</p></div>}
      <div className="requirements"><h4>Still required by the organizer</h4><ul>{op.requirements.map(r=><li key={r}>{r}</li>)}</ul></div></div>}
    {error&&<p role="alert" className="inline-warning">{error}</p>}
    <footer className="detail-footer"><div><a href={op.source} target="_blank" rel="noreferrer">View official requirements <span aria-hidden="true">↗</span></a><time dateTime={op.checkedAt}>Checked {formatDate(op.checkedAt,true)}</time></div><button className="primary" disabled={busy||!fit.canDraft} onClick={onDraft}>{busy?'Preparing draft…':draft?'Refresh grounded draft':'Prepare grounded draft'}</button></footer>
  </section>;
}
